### ISSUE TITLE
NoSuchMethodError: The method 'fetchRow' was called on null.

### ISSUE THREAD

**Issue by djsambo** [TheBosZ/ddo-dart#2]
I received the following error when i tried to fetchall on DDOResults:

```
Unhandled exception:
NoSuchMethodError: The method 'fetchRow' was called on null.
Receiver: null
Tried calling: fetchRow()
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      DDOStatement.fetchAll (package:ddo/statements/ddo_statement.dart:96:26)
```

**Comment by TheBosZ** [comment]
Thanks for the bug report! I'll look into this today.

**Comment by TheBosZ** [comment]
Hmm... I'm having trouble reproducing the error.

Can you give me any more details? Are you using WebSQL or MySQL? Can you give me a small project where the error happens?

**Comment by djsambo** [comment]
I used the documentation example with a mysql database.

**Comment by TheBosZ** [comment]
I pushed an update that tries to fix your issue.

I've also updated the example to be more detailed. Please update and see if that fixes your issue.

In your original report, you said that you "tried to fetchall on DDOResults:"

"fetchAll" is on a DDOStatement, **not** on DDOResults. Make sure you've got the syntax correct.

**Comment by TheBosZ** [comment]
@djsambo Did this fix your issue?

**Comment by TheBosZ** [comment]
Since I haven't heard from you, I'm going to close this issue. If it's still happening, please feel free to reopen.
